# Write a python program for the following:

## a. Print two square matrix of order 3 by taking input from the user

In [2]:
import numpy as np

m1 = np.zeros((3,3), dtype=np.int64)
m2 = np.zeros((3,3), dtype=np.int64)
print("Matrix 1:\n\n",m1)
print("\nMatrix 2:\n\n",m2)

Matrix 1:

 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Matrix 2:

 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
for i in range(len(m1)):
    for j in range(len(m1[0])):
        m1[i][j] = int(input("Enter the number for 1st Matrix: "))

for i in range(len(m2)):
    for j in range(len(m2[0])):
        m2[i][j] = int(input("Enter the number for 2st Matrix: "))


print("\nMatrix 1:\n\n",m1)
print("\nMatrix 2:\n\n",m2)

Enter the number for 1st Matrix: 1
Enter the number for 1st Matrix: 2
Enter the number for 1st Matrix: 3
Enter the number for 1st Matrix: 4
Enter the number for 1st Matrix: 5
Enter the number for 1st Matrix: 6
Enter the number for 1st Matrix: 7
Enter the number for 1st Matrix: 8
Enter the number for 1st Matrix: 9
Enter the number for 2st Matrix: 1
Enter the number for 2st Matrix: 2
Enter the number for 2st Matrix: 3
Enter the number for 2st Matrix: 4
Enter the number for 2st Matrix: 5
Enter the number for 2st Matrix: 6
Enter the number for 2st Matrix: 7
Enter the number for 2st Matrix: 8
Enter the number for 2st Matrix: 9

Matrix 1:

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Perform following operations using numpy functions:

### 1. Addition

In [3]:
add = np.add(m1,m2)
print(add)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### 2. Subtraction

In [4]:
subtract = np.subtract(m1,m2)
print(subtract)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### 3. Multiplication

In [5]:
multiply = np.multiply(m1,m2)
print(multiply)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 4. Division

In [6]:
Division = np.divide(m1,m2)
print(Division)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## c. Perform matrix multiplication using loop

In [9]:
m3 = np.zeros((3,3),dtype = np.int64)
for i in range(3):
    for j in range(3):
        for k in range(3):
            m3[i][j] = m3[i][j] + (m1[i][k]*m2[k][j])
print(m3)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## d. Perform matrix multiplication using numpy function

In [10]:
matmul = m1 @ m2
print(matmul)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## e. Print Transpose of both the matrix

In [11]:
m1_trans = np.transpose(m1)
print("Transpose of Matrix1: \n\n",m1_trans)

m2_trans = np.transpose(m2)
print("\nTranspose of Matrix2: \n\n",m2_trans)

Transpose of Matrix1: 

 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of Matrix2: 

 [[1 4 7]
 [2 5 8]
 [3 6 9]]
