In [1]:
import copy

l = [1,[4,5,6],3,4,5,6]

print(l)

l1 = copy.deepcopy(l)

print(l1)

print(id(l),id(l1))

# l1[1][1] = 23
print(id(l[1]),id(l1[1]))
l2 = l.copy()
print(id(l),id(l2))
print(id(l[1]),id(l1[1]))

[1, [4, 5, 6], 3, 4, 5, 6]
[1, [4, 5, 6], 3, 4, 5, 6]
3051663393728 3051663394752
3051663393984 3051663394560
3051663393728 3051663395008
3051663393984 3051663394560


In [2]:
s = 'Akshay'

d = list(s)

print(d)

d.extend((1,2,3))
print(d)

['A', 'k', 's', 'h', 'a', 'y']
['A', 'k', 's', 'h', 'a', 'y', 1, 2, 3]


In [57]:
dic = {1:"My",2:"Name",3:"is",4:"Akshay"}

dic.update({1:"Akshay"})

print(dic)

{1: 'Akshay', 2: 'Name', 3: 'is', 4: 'Akshay'}


In [4]:
st = input("Enter the String: ")

l1 = list(st)

dic = {}

for i in range(len(l1)):
    dic.update({l1[i]:l1.count(l1[i])})

print(dic)
        

Enter the String: Hello
{'H': 1, 'e': 1, 'l': 2, 'o': 1}


In [5]:
dic={1:'One',2:'Two',3:'Three',4:'Four',5:'Five',6:'Six',7:'Seven',8:'Eight',9:'Nine'}

st=input("Enter the number: ")

l=list(st)

for i in range(len(l)):
    print(dic[int(l[i])])

Enter the number: 123
One
Two
Three


In [9]:
T = ('a','b','c','d')
L = ['A','B','C']

l1 = zip(T,L)

print(l1)
l2 = set(l1)

print(l2)

{('c', 'C'), ('a', 'A'), ('b', 'B')}


In [7]:
import numpy as np

In [14]:
a = np.ones([4,3],dtype = np.int32)
b = np.zeros([4,3],dtype = np.int32)
c= np.arange(0,10)

p = np.concatenate([a,b])

print(p)
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
# a = np.random.random(6)
# print(a)

p = a.ravel()
print(p)

[1 1 1 1 1 1 1 1 1 1 1 1]


In [16]:
a = np.array([1,2,3,4,5,6])
a=a.reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
import pandas as pd

In [18]:
mydata = {
    "car": ["Maruti","Hyundai","Tata"],
    "sterring": [0,1,1]
}

In [19]:
pd_data = pd.DataFrame(mydata)
print(pd_data)

       car  sterring
0   Maruti         0
1  Hyundai         1
2     Tata         1


In [20]:
print(type(pd_data))

<class 'pandas.core.frame.DataFrame'>


In [21]:
print(pd.Series(mydata))

car         [Maruti, Hyundai, Tata]
sterring                  [0, 1, 1]
dtype: object


In [30]:
data = pd.read_csv('data.csv') 

In [31]:
print(pd.options.display.max_rows)

60


In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


In [33]:
data.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [34]:
data.tail()

Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [28]:
data.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [21]:
new_data = data.fillna(130)

In [37]:
print(new_data.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112     130.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [33]:
print(data.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [60]:
l1 = list((1,2,3))
l1

[1, 2, 3]

In [71]:
thislist = ["apple", "banana", "cherry"]
[x for x in thislist]


['apple', 'banana', 'cherry']

In [9]:
f = open('sample.txt','at')
f.write(', Secondly I code in JAVA')
f.close()

In [10]:
f = open('sample.txt','rt')
f.read()
f.close()

In [118]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
x = arr.copy()
y = arr.view()
print(id(x))
print(y.base)
print(arr.base)
arr2 = arr.reshape(5,2)
print(arr2.sum(axis=0,keepdims=True))
arr2.transpose()

1834699631472
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
None
[[25 30]]


array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [82]:
p = np.ones((10,2),dtype=np.int64)
q = np.zeros((10,2),dtype=np.int64)
np.concatenate((p,q),axis=1)
p.astype(float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [81]:
p.sum(axis=1)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [88]:
np.zeros_like(p)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [106]:
a = np.ones((2,2))

In [107]:
a

array([[1., 1.],
       [1., 1.]])

In [108]:
q = np.copy(a.reshape(-1))

In [109]:
q

array([1., 1., 1., 1.])

In [110]:
q[0] = 3
print(q)
print(a)

[3. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [113]:
np.random.random(5) * ((4-1)+1)

array([1.11129673, 1.30120945, 1.75187189, 3.43074411, 2.8877937 ])

In [114]:
q.T

array([3., 1., 1., 1.])

In [121]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(element)
  



print(filter_arr)
#print(newarr)

[43, 44]
